### ISSUE TITLE
[Windows 10]砸壳失败

### ISSUE THREAD

**Issue by xiaokanghub** [a97077088/fd#1]
Frida Version: 15.0.13
Python Version: 3.6
fd Version: 15.0.13
错误如下：
(base) E:\ReProject>fd bagbak 爱思极速版
内核平台:darwin cpu构架:arm64 当前系统:ios(12.4.8)  设备名称:iPhoneg 权限:jailed
Connection closed

**Comment by aadog** [comment]
1.fd不需要python，只需要手机安装frida-server即可
2.你需要先点开app，fd会以附加模式砸壳
3.如果还解决不了，就重启手机
4.再解决不了加qq群: 905979567

**Comment by aadog** [comment]
Restart should be resolved. This is the message that Frida server is stuck
