### ISSUE TITLE
手机上已经安装好了frida 使用WINDOWS环境的时候提示 frida-server: closed

### ISSUE THREAD

**Issue by ReturnHH** [a97077088/fd#3]
e:\test>fd lsapp
内核平台:linux cpu构架:ia32 当前系统:android(5.1.1)  设备名称: 权限:jailed
Unable to connect to remote frida-server: closed

**Comment by aadog** [comment]
权限:jailed ，frida-server没有安装好，系统拿不到root权限,正常权限应该是:full

**Comment by cxapython** [comment]
frida-server的版本和fd版本关系是什么呢

**Comment by aadog** [comment]
frida-server只要大于15.0.8，fd版本随意
