### ISSUE TITLE
脱壳速度极其慢

### ISSUE THREAD

**Issue by xhan** [a97077088/fd#4]
对于有大量小资源文件（1-10k size）的app，脱壳速度慢的无法忍受。
stdout 的原因？

**Comment by aadog** [comment]
把手机不要锁屏,静静等待他脱壳，正常app再5s左右完成，一些资源多的在30s-60s后完成,这已经是所有脱壳中最快的了

**Comment by hello--world** [comment]
也出现了资源文件多的时候，比frida-ios-dump慢太多，不知道啥原因。
